#!/usr/bin/env bash

set -o pipefail
box() { boxes -d ansi -s $(tput cols); }
failed() {
  echo -e "\n\033[1;31mRelease build failed.\033[0m"
  exit 1
}
trap 'failed' ERR

echo -e "\033[1;33mcargo bundle...\033[0m"
cargo bundle --release 2> /dev/null | xargs | box

echo -e "\n\033[1;32mRelease build succeeded.\033[0m"
