#!/usr/bin/env bash

set -o pipefail
box() { boxes -s ${COL:-$(tput cols)}; }
failed() {
  echo -e "\n\033[1;31mRelease build failed.\033[0m"
  exit 1
}
trap 'failed' ERR

# hacky approach for determining whether we're in a nix shell
# since non-nix macOS builders may not want runtime_shaders
if [[ $SHLVL = 2 ]]
then
    RUNTIME_SHADERS=1
else
    RUNTIME_SHADERS=0
fi

echo -e "\033[1;33mcargo bundle...\033[0m"
cargo bundle \
  --release \
  ${RUNTIME_SHADERS:+--features runtime_shaders}

pushd . > /dev/null
cd target/release/bundle/osx/

if [ "$DONT_SIGN" != "true" ]; then
  echo -e "\n\033[1;33msigning app...\033[0m"
  codesign -s "$CERT_IDENTITY" alc-calc.app
fi

if test -f alc-calc.dmg; then
  echo -e "\n\033[1;33mremoving old dmg...\033[0m"
  rm -f alc-calc.dmg
fi

echo -e "\n\033[1;33mcreating dmg...\033[0m"
create-dmg \
  --app-drop-link 95 25 \
  --icon alc-calc.app 265 25 \
  --icon-size 50 \
  --text-size 12 \
  --window-pos 520 405 \
  --window-size 920 435 \
  alc-calc.dmg \
  . \
  &> /dev/null

readlink -f alc-calc.dmg | box

if [ "$DONT_SIGN" != "true" ]; then
  echo -e "\n\033[1;33msigning dmg...\033[0m"
  codesign -s "$CERT_IDENTITY" alc-calc.dmg
fi

popd > /dev/null

echo -e "\n\033[1;32mRelease build succeeded.\033[0m"
